### ISSUE TITLE
Error after installing('nvim-tree.diagnostics')

### ISSUE THREAD

**Issue by im-AMS** [ChristianChiarulli/Neovim-from-scratch#1]
I just uninstalled lunarvim and started my config.

Packer Installed all its stuffs, then after reopening I get this 
`Vim(autocmd):E216: No such group or event: DiagnosticChanged * lua require'nvim-tree.diagnostics'.update()`

How do I fix this?

On OSX 12.1
Nvim V0.6.0-dev+525

**Comment by ChristianChiarulli** [comment]
Maybe you need the release version of 0.6?

**Comment by im-AMS** [comment]
Oh yess, the stable version of neovim works!
