### ISSUE TITLE
autochdir

### ISSUE THREAD

**Issue by bdillahu** [ChristianChiarulli/Neovim-from-scratch#10]
I'm sure this is a user error, but how can you get autochdir to work right (my definition of right :-))?

By default, it seems to be turned off.

I added an option to turn it on.

I

> echo &autochdir

and it shows 

1

for enabled... but it shows root of project instead of current director.

Then if I manually 

:set autochdir

It works like I want...

Help?

**Comment by ChristianChiarulli** [comment]
play around with the project plugin

**Comment by bdillahu** [comment]
Thanks, that got it (set manual mode in the project plugin)...
