### ISSUE TITLE
Comments key mappings are not working.

### ISSUE THREAD

**Issue by fdelacruz** [ChristianChiarulli/Neovim-from-scratch#11]
The default key mappings are not working. **g** is being used by _which-key_ and the new key mappings for linewise  commenting is **gcA** which is very difficult to hit and anyways, is not working well because the "g" starts _which-key_. The same with the rest of the key mappings for commenting.
<img width="619" alt="Screen Shot 2021-12-19 at 7 37 09 PM" src="https://user-images.githubusercontent.com/148098/146696897-ebbefb98-5050-4829-b81f-c6a952068ff5.png">

**Comment by ChristianChiarulli** [comment]
https://github.com/ChristianChiarulli/nvim/blob/master/lua/user/whichkey.lua these maps may help for now, when I get to the comments video I'll take a closer look at this.

**Comment by fdelacruz** [comment]
No commenting key maps there, but ok.

**Comment by ChristianChiarulli** [comment]
https://github.com/ChristianChiarulli/nvim/blob/b66561480f2256056109f991f406f3b8eb3a2f18/lua/user/whichkey.lua#L115

**Comment by fdelacruz** [comment]
Thank you!!
