### ISSUE TITLE
Wrong keymapping for moving lines

### ISSUE THREAD

**Issue by Ka-lip** [ChristianChiarulli/Neovim-from-scratch#111]
Hello guys,

I just followed your YouTube video and found small bugs.

https://github.com/LunarVim/Neovim-from-scratch/blob/e1ac27496fccd2e0accb79c6ac2097865feff14b/lua/user/keymaps.lua#L50-L51

It should be 
```lua
keymap("v", "<A-j>", ":m '>+1<CR>gv=gv", opts)
keymap("v", "<A-k>", ":m '<-2<CR>gv=gv", opts)
```

The original setting does not work especially if you select multiple lines in visual mode. Check detail from [VimTips](https://vim.fandom.com/wiki/Moving_lines_up_or_down)

Please correct me if I am wrong.

Thank you very much for the vidoes. They do help me a lot!

(I am happy to submit a PR but not sure how to fix this to all branches because all branches have the same mistake.)

Best regards,
Ka-lip

**Comment by li-yi-dong** [comment]
Exactly the same issue for me. I solved after [https://vim.fandom.com/wiki/Moving_lines_up_or_down]

**Comment by LiinXemmon** [comment]
Hi, I  have some questions about these key bindings.
I found there are some `gv-gv`s in 
 ```
-- Visual Block --
-- Move text up and down
keymap("x", "J", ":move '>+1<CR>gv-gv", opts)
keymap("x", "K", ":move '<-2<CR>gv-gv", opts)
keymap("x", "<A-j>", ":move '>+1<CR>gv-gv", opts)
keymap("x", "<A-k>", ":move '<-2<CR>gv-gv", opts)
```
 I think they are the same as `gv`. Are these typos?

I found the key bindings set in block mode also worked in visual mode and vice versa. Is there any fallback in these modes?

**Comment by gnmearacaun** [comment]
fixed now, thanks!
