### ISSUE TITLE
cmp plugin confgs boken after ugrading to nvim 0.7

### ISSUE THREAD

**Issue by shrkamat** [ChristianChiarulli/Neovim-from-scratch#113]
I see deprecation error with `documentation` [here](https://github.com/LunarVim/Neovim-from-scratch/blob/master/lua/user/cmp.lua#L122)

Further I am unable to use arrow keys for scrolling through completion list.

**Comment by RedCode-123** [comment]
You have to delete this part of the code in the ~/.config/nvim/lua/user/cmp.lua file:

``
 documentation = {
    border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  }
``

and it fix the problem.

**Comment by shrkamat** [comment]
Thanks, that fixes the warning. However arrow key is not working for scrolling through completion list. I have to use tab keys.

**Comment by jcuenod** [comment]
The deprecation notice explains the solution. Take a look at PR #112 to see how to solve without deleting the line.

**Comment by gettingStarted77** [comment]
`  window = {
    documentation = {
      border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
    },
  },
`

**Comment by VowelMovement** [comment]
The mapping can be fixed like [this](https://github.com/LunarVim/LunarVim/commit/bc90e8174fd1760d87b5cd68d8fabb9669ab5fb9).

```
mapping = cmp.mapping.preset.insert {
      ["<C-k>"] = cmp.mapping.select_prev_item(),
      ["<C-j>"] = cmp.mapping.select_next_item(),
etc...
```

**Comment by shrkamat** [comment]
@VowelMovement  thanks it worked. My changes for others ref

https://github.com/shrkamat/nvim/commit/d68eb6dfe761cfb54317f60c548a7ee6e7c6aa34
