### ISSUE TITLE
nvim-cmp documentation deprecation issue

### ISSUE THREAD

**Issue by Rathersilly** [ChristianChiarulli/Neovim-from-scratch#118]
On nvim startup I got this message:
[nvim-cmp] documentation is deprecated.
[nvim-cmp] Please use window.documentation= "native" instead.

This lead to an error message when pressing tab to autocomplete (bad arguments in a nvim-cmp lua function).
The deprecated feature is documented here: https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1098149666

Changing this code in lua/user/cmp.lua from:

```
documentation = {
    border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
},
```

to 

```
window = {
    documentation = {
        border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
        }
},
```
fixed the issue for me.
Hope this helps someone, and this project is awesome!

**Comment by mhmdali102** [comment]
Thank you it works for me

**Comment by aflyingpumpkin** [comment]
Just saw this, you can do this a bit simpler by using this code:
```lua
  window = {
    documentation = cmp.config.window.bordered(),
  }
  ```
  I submitted a PR containing this  #117

**Comment by aflyingpumpkin** [comment]
#112 and #115 also fix this using the method mentioned here.

**Comment by brianrobt** [comment]
So does #146.  Maybe we can get one of them merged soon.
