### ISSUE TITLE
Error detected while processing /home/itsrxmmy/.config/nvim/init.lua

### ISSUE THREAD

**Issue by sandbands** [ChristianChiarulli/Neovim-from-scratch#120]
I ran neovim and got the following error message

```
rror detected while processing /home/itsrxmmy/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim.lua:63: /home/itsrxmmy/.config/nvim/lua/user/cmp.lua:127: '}' expected (to close '{' at line 48) near 'experimental'
stack traceback:
        [C]: in function 'error'
        vim.lua:63: in function <vim.lua:57>
        [C]: in function 'require'
        /home/itsrxmmy/.config/nvim/init.lua:5: in main chunk
Error detected while processing /home/itsrxmmy/.local/share/nvim/site/pack/packer/start/Comment.nvim/after/plugin/Comment.lua:
E5113: Error while calling lua chunk: .../pack/packer/start/Comment.nvim/after/plugin/Comment.lua:1: attempt to index field 'keymap' (a nil value)
stack traceback:
        .../pack/packer/start/Comment.nvim/after/plugin/Comment.lua:1: in main chunk
Press ENTER or type command to continue
```

it happens every time i open Neovim and has become really annoying

**Comment by vurtune** [comment]
/home/itsrxmmy/.config/nvim/lua/user/cmp.lua:**127**: **'}' expected** (to close '{' at line 48) near 'experimental'

Do what it says.

**Comment by euler007** [comment]
Hey apologies in advance if this is repeat or basic i am new to lua. I am not sure what is causing the following error, I have copied your cmp.lua file from  05-Completion branch, as is, along with that I have added the plugins and added it to the init.lua but its throwing the following error any clue as to how i can fix this?

<img width="1004" alt="Screenshot 2022-06-10 at 8 52 51 PM" src="https://user-images.githubusercontent.com/20284507/173098588-4776eb84-1626-4e0a-a92b-eaaa48c75034.png">
