### ISSUE TITLE
02-keymaps alt + j alt + k not working on mac

### ISSUE THREAD

**Issue by yepes** [ChristianChiarulli/Neovim-from-scratch#127]
Following the video https://www.youtube.com/watch?v=435-amtVYJ8&list=PLhoH5vyxr6Qq41NFL4GvhFp-WLd5xzIzZ&index=3

once you reach to the part 
```lua 
-- Move text up and down
keymap("v", "<A-j>", ":m .+1<CR>==", opts)
keymap("v", "<A-k>", ":m .-2<CR>==", opts)

-- Visual Block --
-- Move text up and down
keymap("x", "J", ":move '>+1<CR>gv-gv", opts)
keymap("x", "K", ":move '<-2<CR>gv-gv", opts)
keymap("x", "<A-j>", ":move '>+1<CR>gv-gv", opts)
keymap("x", "<A-k>", ":move '<-2<CR>gv-gv", opts)
```

The uppercase one seems to work, but the alt + j / k don't seem to be working.

**Comment by JannatinNaimX3** [comment]
If you're on Mac and are using iTerm, there's an option to use the left option key as alt.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/93467756/165958624-1caad0bb-020c-4392-b6ce-2c98e0618643.png">

Set left option key to Esc+. Worked for me.

**Comment by yepes** [comment]
That doesn't seem to have anything to do with what i asked.

alt key is working fine on other shortcuts. The problem is that <A+k> is mapped on iterm to edit -> Clear Buffer

![image](https://user-images.githubusercontent.com/1114453/165987201-0e81a7bf-c473-4cf0-ab3c-06f233cf42f0.png)

So I will just remap it to something else.

Thanks anyway!

**Comment by yepes** [comment]
Just trying this a bit further. I'm not able to map anything using the alt key. anyone else using mac has the same problem?

**Comment by JannatinNaimX3** [comment]
```lua
-- Move selected text up and down.
keymap("v", "<A-j>", ":m .+1<CR>==", opts)
keymap("v", "<A-k>", ":m .-2<CR>==", opts)
keymap("v", "p", '"_dP', opts)

-- Move selected lines up and down.
keymap("x", "<A-j>", ":move '>+1<CR>gv-gv", opts)
keymap("x", "<A-k>", ":move '<-2<CR>gv-gv", opts)
```

Here's what I've been using and it works. Give it a shot.

**Comment by yepes** [comment]
Thanks for the response @JannatinNaim 

No, it doesn't work. I'm using a mac with iterm2. By alt key I mean the option mac key (two keys left from space) that every mac has. That key doesn't seem to be working with any keymap.

**Comment by JannatinNaimX3** [comment]
I get you. I too use a Mac and I got it working like that. Strange why it doesn't work for you.
You should check System Preferences > Keyboard > Shortcuts for any system keybind that's being used. (idk, probably not but just to be sure)

**Comment by yepes** [comment]
I have an spanish keyboard, I don't know if that has anything to do. I just tried another keys with alt and any of them work.

Just to confirm. Can you please go to iterm and then press ctrl+v and after that alt+j?

If I do that I get this symbol: ¶

**Comment by JannatinNaimX3** [comment]
owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww. I figured out what's your issue. IDK what exactly it's called but something like "accented characters" maybe. I turn that thing off as it bothers me and enable key repeat instead. This requires a third party app [TinkerTool](https://www.bresink.com/osx/0TinkerTool/download.php). Install that and there's the option to turn that off.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/93467756/166057097-db1d3e23-2be6-4205-8a7e-fd801a48e14a.png">

Give this a try. Pretty sure this is what you're looking for. (If not, this tool has some other neat options too, so "tinker" around. 😆)

**Comment by yepes** [comment]
mmm i would like to solve this without adding third party apps

**Comment by JannatinNaimX3** [comment]
There's a command for turning that off, I just can't remember it and use that app. 😆

**Comment by JannatinNaimX3** [comment]
https://osxdaily.com/2011/08/04/enable-key-repeat-mac-os-x-lion/
@yepes check this out.

**Comment by yepes** [comment]
nothing, same result.

**Comment by JannatinNaimX3** [comment]
:) Now this is just a huge pain.

**Comment by yepes** [comment]
If anyone comes here with the same problem. It ended up being iTerm2. I finally got it working on both iterm and terminal

**iTerm2**:
- Preferences -> Profiles -> keys -> General and activate Left option key as esc+ (as @JannatinNaim suggested).
- If you are using an external usb keyboard, you have to also check "right option key as esc+". If you are using a MBP, you don't have to choose this option.

**terminap.app**
- Preferences -> profiles -> keyboard -> check "Use option as meta key"

**Comment by JannatinNaimX3** [comment]
Told you it's a common issue. Glad it's fixed. 😉
