### ISSUE TITLE
Taking away all the user. from init.lua causes issues.

### ISSUE THREAD

**Issue by thepenguinthatwants** [ChristianChiarulli/Neovim-from-scratch#13]
Hi Chris!
This project looks and works very well and really eases up setting own stuff.
The lua folder feels bit obsolete and moving files and folder from user folder to higher level causes issues after taking away all the user. statements from init.lua.

Is there a reason for creating and using user folder instead of moving it to higher level??

**Comment by JohnVillalovos** [comment]
This was discussed in his video: https://www.youtube.com/watch?v=hY5-Q6NxQgY

**Comment by JohnVillalovos** [comment]
Specifically he discusses it at this point: https://youtu.be/hY5-Q6NxQgY?t=115

**Comment by thepenguinthatwants** [comment]
Ah my bad didn't watch that yet
