### ISSUE TITLE
leader key does not work

### ISSUE THREAD

**Issue by girishji** [ChristianChiarulli/Neovim-from-scratch#134]
Please remove the following line from options.lua
timeoutlen = 100,                        -- time to wait for a mapped sequence to complete (in milliseconds)

with the above line <leader> key (space) mapped to something the opens a popup (say Telescope find_files) will not work.

**Comment by gnmearacaun** [comment]
try setting `timeoutlen = 300` or even 1000,

**Comment by azinsharaf** [comment]
`timeoutlen = 300` worked for me! Thanks.
