### ISSUE TITLE
treesitter gives error

### ISSUE THREAD

**Issue by girishji** [ChristianChiarulli/Neovim-from-scratch#135]
following line in treesitter.lua should be modified to specify languages
ensure_installed = { "maintained" },

https://issuemode.com/issues/nvim-treesitter/nvim-treesitter/78109062

**Comment by antonio-hickey** [comment]
Inside the treesitter.lua file:

Replace `ensure_installed = "maintained"`
With `ensure_installed = { "lua", "*LANGUAGE1*", ... "*LANGUAGE N*"}`

_Note: "*LANGUAGE*" is just a place holder, replace this with your desired language._

**Comment by girishji** [comment]
maybe use ensure_installed = "all". leaving it as "maintained" gives error

**Comment by antonio-hickey** [comment]
I'm not suggesting to leave it as "maintained", I'm saying I fixed this error by specifying my languages. Using "all" is probably better but I just specified the languages I actually use.

**Comment by oleg-medovikov** [comment]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/57829409/167266723-01414c43-c8a3-41d7-9bbe-546c791fdcb6.png">

**Comment by habsfanongit** [comment]
Had the same error with a fresh install. Changing `ensure_installed = "maintained"` to `ensure_installed = "all"` resolved the error for me.

**Comment by lv8pv** [comment]
Same error, fixed it as mention above

**Comment by antonio-hickey** [comment]
This issue should be closed, I believe it was fixed with https://github.com/LunarVim/Neovim-from-scratch/pull/152

**Comment by gnmearacaun** [comment]
> This issue should be closed, I believe it was fixed with #152

It is addressed in #131
