### ISSUE TITLE
gcc commenting doesn't seem to work

### ISSUE THREAD

**Issue by thepenguinthatwants** [ChristianChiarulli/Neovim-from-scratch#14]
Using the master branch.
I've tried using gcc command on python type of files, but it seems to not do anything.

ts_context_commentstring plugin and the settings should allow it to work. But something seems to be missing.
I am using nvim 0.6 version.

**Comment by gikari** [comment]
I am encountering the same behavior with this config. You closed the issue, so I assume you fixed the problem. What did you do to do that?

**Comment by gikari** [comment]
I managed to fix the issue by enabling all presets in `whichkey.lua`:
```lua
    presets = {
      operators = true, -- adds help for operators like d, y, ... and registers them for motion / text object completion
      motions = true, -- adds help for motions
      text_objects = true, -- help for text objects triggered after entering an operator
      windows = true, -- default bindings on <c-w>
      nav = true, -- misc bindings to work with windows
      z = true, -- bindings for folds, spelling and others prefixed with z
      g = true, -- bindings for prefixed with g
    },
```
operators, motions and text_objects were disabled by default.
