### ISSUE TITLE
Neovim version required to use this config maybe needs to be updated

### ISSUE THREAD

**Issue by brianrobt** [ChristianChiarulli/Neovim-from-scratch#147]
In the README, it states "IMPORTANT Requires [Neovim v0.6.0](https://github.com/neovim/neovim/releases/tag/v0.6.0) or [Nightly](https://github.com/neovim/neovim/releases/tag/nightly)".  However, I have been seeing a lot of issues (including myself) where this config doesn't completely work with even 0.7.0.

Perhaps the documentation needs to be updated to 0.8.0?

**Comment by gnmearacaun** [comment]
Best put in a PR?

**Comment by gnmearacaun** [comment]
#149 has you covered

**Comment by brianrobt** [comment]
Thanks for doing that.  Just wanted to make sure that we weren't the only ones running into these issues.  Team Bleeding Edge! 😆

**Comment by gnmearacaun** [comment]
My pleasure. Crawling through these issues is like learning to walk. Solving them is like learning to fly. Team Soaring Eagle! :eagle:
