### ISSUE TITLE
Lsp config deprecated setting regarding accessing client.resolved_capabilities setting

### ISSUE THREAD

**Issue by drusmanbashir** [ChristianChiarulli/Neovim-from-scratch#148]
On starting neovim 0.8, and after applying lsp related updates in your repo, I  still get the following error:
![error](https://user-images.githubusercontent.com/5282314/167918776-15479210-6ca6-4380-bc51-c316f775bb59.png)

The is due to the following codeblock in lsp/handlers.lua file:

```
local function lsp_highlight_document(client)
  -- Set autocommands conditional on server_capabilities
  if **_client.resolved_capabilities._**document_highlight then
    vim.api.nvim_exec(
      [[
      augroup lsp_document_highlight
        autocmd! * <buffer>
        autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()
        autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
      augroup END
    ]],
      false
    )
  end
end
```

**Comment by gnmearacaun** [comment]
@drusmanbashir This commit https://github.com/LunarVim/Neovim-from-scratch/pull/144/commits/fc52e86ef482c2db5a7b75707a407730245d3a63 in PR #144 will fix the error if you want to manually edit your handlers.lua

**Comment by vijayd** [comment]
There's a simpler fix. Just replace with following:
  -- if client.resolved_capabilities.document_highlight then
  if client.server_capabilities.documentHighlightProvider then

Similarly,
--    client.resolved_capabilities.document_formatting = false
    client.server_capabilities.documentFormattingProvider = false
