### ISSUE TITLE
[nvim-cmp] documentation is deprecated

### ISSUE THREAD

**Issue by mingzeyang** [ChristianChiarulli/Neovim-from-scratch#158]
Neovim version : v0.7.0

Following youtube tutorial in section 05-comletion, I met this 

![1653387477(1)](https://user-images.githubusercontent.com/106152692/170009222-9d9db39c-2e9f-4697-8671-47190d81c2e3.jpg)

sloved it simply  by following [How so I resolve the "documentation is deprecated" message in Neovim 0.7?](https://www.reddit.com/r/neovim/comments/u5onwt/how_so_i_resolve_the_documentation_is_deprecated/)

```diff
-  documentation = {
-    border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
+  window = {
+    documentation = {
+      border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
+    }
```

**Comment by lv8pv** [comment]
window, not windos worked for me

**Comment by mingzeyang** [comment]
> window, not windos worked for me

thanks, I typed this git diff snippet with Grammarly off 😂

**Comment by Kamil-Herbetko** [comment]
That worked for me. Thank You!

**Comment by d13g0** [comment]
Hi, this worked for me, in `cmp.lua`

```lua

  -- documentation = {
  -- border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
   --},
   window = {
    documentation = cmp.config.window.bordered(),
  },
```

**Comment by gnmearacaun** [comment]
@d13g0 updated to your suggestion
