### ISSUE TITLE
Leader - q not quitting 

### ISSUE THREAD

**Issue by Ramilito** [ChristianChiarulli/Neovim-from-scratch#16]
Pressing leader then q should quit nvim but instead I get a new silce at the bottom:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/8473233/146943931-29018ac8-3f95-42ca-b23c-d1e8eeefcec5.png">

Using Ubuntu with WSL.
Lunarvim is working, and it works if I comment out:
```
require "user.lsp"
```

**Comment by gitavk** [comment]
May be the question is to WSL?

**Comment by Ramilito** [comment]
Don’t think so, I mean lunarvim is working great and typing :q works as well

**Comment by ChristianChiarulli** [comment]
It's an LSP binding in handlers

**Comment by Ramilito** [comment]
I see it now, guess I’ll just remove that line?

**Comment by kaizerx31** [comment]
I am facing the same issue leader q isnt quiting and instead opens up location list diagnostics
