### ISSUE TITLE
"maintained" seem to be removed as an option?

### ISSUE THREAD

**Issue by reaper8055** [ChristianChiarulli/Neovim-from-scratch#168]
`ensure_installed = "maintained"` doesn't seem to work anymore, maybe after this [commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/acd01551a3185118f58f0708b7fffdb2465e39f1)?

Although this works fine: 
```lua
ensure_installed = [ all | list... ]
``` 

https://github.com/LunarVim/Neovim-from-scratch/blob/3efda23509a4ac2e0673d8142955dda040b6147a/lua/user/treesitter.lua#L7

**Comment by tlelson** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1113959051

Really appreciate the config.  I was hoping to use it as a template of my own configuration.  Which branch is your daily driver?

**Comment by reaper8055** [comment]
I use the master branch and just fixed all the errors in my config, you can check it out [here](https://github.com/reaper8055/nvim-config).

I generally update all the plugins to latest version just to avoid major parity later down the road.

**Comment by Mat-moran** [comment]
Thanks @reaper8055 for pointig this out. I tryed your treesiter config with "all" but it did not work for me. 
I solve it using a list of languages `  ensure_installed = {"python", "lua", "rust"}` as they say in the treesiter commit you pointed.

**Comment by ChristianChiarulli** [comment]
this is fixed now
