### ISSUE TITLE
vim.lsp.diagnostic.set_loclist is deprecated

### ISSUE THREAD

**Issue by Ph3ngz0r** [ChristianChiarulli/Neovim-from-scratch#170]
A error happened when open a quickfix using hotkey: \<leader\> l q,
![截屏2022-06-08 02 10 32](https://user-images.githubusercontent.com/31665078/172454150-e1318dd0-816f-4959-8f58-851203f05e4c.JPG)

**solve:**
modify lua/user/whichkey.lua: 154
 `q = { "<cmd>lua vim.lsp.diagnostic.set_loclist()<cr>", "Quickfix" },`
to
 `q = { "<cmd>lua vim.diagnostic.setloclist()<cr>", "Quickfix" },`

**Comment by gnmearacaun** [comment]
fixed now. thank you @Ph3ngz0r
