### ISSUE TITLE
Rust-analyzer Issue

### ISSUE THREAD

**Issue by JojiiOfficial** [ChristianChiarulli/Neovim-from-scratch#171]
I'm not sure where exactly this error comes from but It'll probably also affect other users using this config I'm reporting it here.

When writing in rust (using rust-analyzer and mostly standard configurations) following error appears: 

https://user-images.githubusercontent.com/15957865/172685996-057f0a47-d95b-40b4-a149-b699fed796c5.mp4

In most cases it appears when writing `self.` within a function taking `&self` as parameter. 

 This is my config:
https://github.com/JojiiOfficial/nvim-config

I haven't changed much. Most changes are just formatting changes.
Since this error appears quite often its hard to use vim to code in rust. 

From which plugin does this error come from? Is there a way to hide this error (or even fix it)?

**Comment by ryan-WORK** [comment]
@JojiiOfficial I believe you should post that error over here:
https://github.com/rust-lang/rust-analyzer

**Comment by JojiiOfficial** [comment]
Was indeed a rust-analyzer issue which has been fixed
