### ISSUE TITLE
remove color scheme

### ISSUE THREAD

**Issue by pedromaironi** [ChristianChiarulli/Neovim-from-scratch#172]
How i can change this color?
![image](https://user-images.githubusercontent.com/43529059/172935963-4d1b656e-4eee-4dbc-8715-4f1b652940d6.png)

**Comment by pedromaironi** [comment]
Blue color to white or anyelse

**Comment by ljden** [comment]
That is known as the gutter or signs column. You can change the highlight colour like so:
`vim.cmd [[highlight ColorColumn guibg=white]]`
For other colours `:help gui-colors` gives
```
							*gui-colors*
	Suggested color names (these are available on most systems):
	    Red		LightRed	DarkRed
	    Green	LightGreen	DarkGreen	SeaGreen
	    Blue	LightBlue	DarkBlue	SlateBlue
	    Cyan	LightCyan	DarkCyan
	    Magenta	LightMagenta	DarkMagenta
	    Yellow	LightYellow	Brown		DarkYellow
	    Gray	LightGray	DarkGray
	    Black	White
	    Orange	Purple		Violet

	You can also specify a color by its RGB (red, green, blue) values.
	The format is "#rrggbb", where
		"rr"	is the Red value
		"gg"	is the Green value
		"bb"	is the Blue value
	All values are hexadecimal, range from "00" to "ff".  Examples: >
  :highlight Comment guifg=#11f0c3 guibg=#ff00ff
```

Sources: 
Neovim docs
https://stackoverflow.com/a/15278468/6946577 
https://www.reddit.com/r/neovim/comments/me35u9/comment/gsd5x20/

**Comment by pedromaironi** [comment]
Thank u man, I appreciate this, sorry for answer too late.
