### ISSUE TITLE
lsp-signature HELP

### ISSUE THREAD

**Issue by euler007** [ChristianChiarulli/Neovim-from-scratch#174]
Hi,

I have been following your series, thanks for that! I am new to lua type config.

I am trying to install this plugin called lsp-signature ("ray-x/lsp_signature.nvim/") and there are 2 problems I am facing:

1. It works but it clashes with the cmp autocompletion and there are 2 floating windowa
2. I can not figure out where to place the lsp-signature config

Hoping someone can help

**Comment by euler007** [comment]
solved🙂

**Comment by pmav99** [comment]
maybe you should post your solution so that others facing the same problem may benefit from your research

**Comment by euler007** [comment]
Sure, happy to help. Asssuming you are using the similar file structure as the project add the following in lsp.handler.lua inside the m.attach function

`  require'lsp_signature'.on_attach({
        ...
        lsp_signature config here
       ...
  })

`

PS: Also checkout [this library](https://github.com/hrsh7th/cmp-nvim-lsp-signature-help) works well with cmp
