### ISSUE TITLE
error running nvim after cloning repo

### ISSUE THREAD

**Issue by scorbin** [ChristianChiarulli/Neovim-from-scratch#176]
I ran the following command on ubuntu 20.04 server and got the followg error.
```
git clone https://github.com/LunarVim/Neovim-from-scratch.git ~/.config/nvim
nvim
```                                                                                                                                                                                                
Error detected while processing /home/scorbin/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:373: Parser not available for language maintained
stack traceback:
        [C]: in function 'get_parser_install_info'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:373: in function 'install_lang'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:419: in function 'ensure_installed'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:388: in function 'setup'
        /home/scorbin/.config/nvim/lua/user/treesitter.lua:6: in main chunk
        [C]: in function 'require'
        /home/scorbin/.config/nvim/init.lua:8: in main chunk

**Comment by filahf** [comment]
I had the same issue, but https://github.com/LunarVim/Neovim-from-scratch/issues/130 did the trick for me.

**Comment by ChristianChiarulli** [comment]
should be fixed now
