### ISSUE TITLE
warning different multiple client offset encoding detected for buffer, this is not supported yet

### ISSUE THREAD

**Issue by Ch4kr4k** [ChristianChiarulli/Neovim-from-scratch#185]
Need Help please 
whenever i try to open any c/c++ files
it spams this warning
```
warning different multiple client offset encoding detected for buffer, this is not supported yet
```
i havent made any change to any of the lua files
## screenshot
![Screenshot_2022-06-25_20_08_51](https://user-images.githubusercontent.com/32250841/177006049-c4846529-bbb4-427f-a17f-f14cdff1947a.png)

**Comment by Ch4kr4k** [comment]
hopping for solution
thank you

**Comment by p4p3r** [comment]
@BL4CK-R34P3R did you find a solution?

**Comment by Ch4kr4k** [comment]
> @BL4CK-R34P3R did you find a solution?

I did but I forgot how I did it
