### ISSUE TITLE
:checkhealth Command throwing Errors.

### ISSUE THREAD

**Issue by ghost** [ChristianChiarulli/Neovim-from-scratch#2]
Running :checkhealth throws following output
```
Running healthchecks...
Error detected while processing function health#check:
line   37:
E684: list index out of range: 0
Press ENTER or type command to continue
```
Other Things are working fine!
Maybe its just that i did something stupid.

**Comment by bdillahu** [comment]
Same here, for what it's worth. 

Otherwise, great setup - this may very well replace my homegrown config! Simple and effective.

**Comment by sigmaSd** [comment]
You probably have files under `~/.local/share/nvim` you can just move that folder out to test

**Comment by bdillahu** [comment]
I had removed all of ~/.local/share/nvim before loading this config... so whatever is there it created.

But I just re-ran it and checkhealth is now working - not sure what changed. I had tried several times yesterday, but now it's happy, so...

Thanks!

**Comment by JohnVillalovos** [comment]
The fix for me was to do the following:

First run `nvim` twice to make sure everything is installed and tree-sitter has compiled everything.

Then start `nvim` and do the following:

```
:LspInstall pyright
```

You can install any LSP server you want, but I use Python so I did pyright.

After I did that I could then do `:checkhealth`

I tested this in the Docker container I created to try this out. See https://github.com/LunarVim/Neovim-from-scratch/pull/8

**Comment by ghost** [comment]
Alright I figured out everything!
This error occurs because npm or LSP is not installed.
Make sure you have `npm`, `node` and `cargo` installed on your system.
I found these prerequisites from [lunarvim's Documentation](https://www.lunarvim.org/01-installing.html#prerequisites)

On Arch install following packages:
```bash
sudo pacman -S npm nodejs rust
```
Also [Resolve EACCES permissions when installing packages globally](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) to avoid error when installing

Then run `nvim` and install a language server of your choice
```
:LspInstall sumneko_lua
```
I am installing LSP for lua here.
Or run `:LspInstallInfo` for list of all available LSPs.

Chris should add a prerequisites section in README.md
