### ISSUE TITLE
Some refactorings possible in options + an explanation

### ISSUE THREAD

**Issue by TonioGela** [ChristianChiarulli/Neovim-from-scratch#20]
Hello! First of all, thanks for the series. It's awesome.

I did some researches to understand why (according to your TODO) format options are not working:
https://github.com/LunarVim/Neovim-from-scratch/blob/8cebbf6b111b664aecf8a29039c483ae4db5afe7/lua/user/options.lua#L46

I discovered that neovim internally has a plugin named `ftplugin` that should stand for "filetype plugin" that dispatches (between the others) the format options for a specific file format. Neovim loads the plugin AFTER your custom configuration, so once you open a file with a recognized extension, the configuration is overridden.

The only documented way that I found to override this behaviour in Neovim (since `autocmd FileType * set formatoptions=` doesn't work as it does in vim) is described [here](https://neovim.discourse.group/t/disable-comment-auto-insertion/892/5), and it involves adding parameters to the `ftplugin` configuration section that is loaded after the plugin, that appears to be language-specific, i.e. for Lua `~/.config/nvim/after/ftplugin/lua.lua`
`:help runtimepath` contains some more information about these files that are executed at runtime. I haven't still figured out how to set these options globally sadly.

**Bonus section**
This section:
https://github.com/LunarVim/Neovim-from-scratch/blob/8cebbf6b111b664aecf8a29039c483ae4db5afe7/lua/user/options.lua#L44-L45
can be rewritten in pure lua as
```lua
vim.opt.whichwrap:append "<,>,[,],h,l"
vim.opt.iskeyword:append "-"
```

**Comment by kylo252** [comment]
> I haven't still figured out how to set these options globally sadly.

Interesting, I thought this works already since we had an issue related to it at some point. https://github.com/LunarVim/LunarVim/blob/7d1b2f697b70cd81adb34c734a6e02fdf991d2db/lua/lvim/core/autocmds.lua#L30-L36

> can be rewritten in pure lua as
> ```lua
> vim.opt.whichwrap:append "<,>,[,],h,l"
> vim.opt.iskeyword:append "-"
> ```

Nice one, thanks! It's overdue that we update this, at least in lvim.
