### ISSUE TITLE
nvim-ts-context-commentstring failing

### ISSUE THREAD

**Issue by umop3plsdn** [ChristianChiarulli/Neovim-from-scratch#203]
Every time I run the initial setup this keeps failing even though it's spelled right and the github exists still. Also, :CheckHealth has a bunch of stuff missing like prettier and some other things

**Comment by Rz-Rz** [comment]
Same for me, breaking changes might have been introduced for null-ls I think

**Comment by umop3plsdn** [comment]
no longer an issue
