### ISSUE TITLE
What happened to LSP's default keymappings?1

### ISSUE THREAD

**Issue by jeffsaremi** [ChristianChiarulli/Neovim-from-scratch#206]
Or any key mappings for that matter. None of `gd`, `gD` and so on work. Instead a window pops up (with a terrible color contrast) giving us options none of which include LSP actions

**Comment by ddfonseca** [comment]
Change your `timeoutlen` to `300` to wait for a mapped sequence to complete. So, maybe it's too fast and you aren't typing `g` and `d` fast enough.

**Comment by kamalkech** [comment]
@ddfonseca which file that need to change timeoutlen ?

**Comment by ddfonseca** [comment]
@kamalkech if you follow the convention of neovim-from-scratch, it's in `lua/user/options.lua`

**Comment by gnmearacaun** [comment]
`timeoutlen` was increased to 300ms in #241, so closing this
