### ISSUE TITLE
Error setting up LSP

### ISSUE THREAD

**Issue by dotzenith** [ChristianChiarulli/Neovim-from-scratch#21]
I'd like to say thank you for all the work you put into this series! 

I tried to give the config a shot by using the git clone command provided in the readme. For some reason, I'm getting the following error

```Error detected while processing /Users/username/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/username/.config/nvim/lua/user/lsp/init.lua:7: attempt to index a
boolean value
stack traceback:
        /Users/username/.config/nvim/lua/user/lsp/init.lua:7: in main chunk
        [C]: in function 'require'
        /Users/username/.config/nvim/init.lua:6: in main chunk
```

Any idea why that could be the case?

**Comment by Al3bad** [comment]
probably from the typo in [jsonls.lua](https://github.com/LunarVim/Neovim-from-scratch/blob/master/lua/user/lsp/settings/jsonls.lua#L2) file in the second line.



make sure to provide the correct path in `pcall` ... so it should look like this:

```lua
local status_ok, jsonls_settings = pcall(require, "lsp.settings.jsonls")
```

**Comment by Nokodoko** [comment]
This is an awesome series, thank you Chris! I'll be visiting your Patreon.

To answer the above question, I had a similar issue, which was resolved by using the nightly version of neovim (you have to compile from source off of the github site). 

I hope this helps.

**Comment by Jacob3075** [comment]
Having the same issue
tried @Nokodoko's solution and it didn't work
Installed neovim from AUR (neovim-nightly-bin)
Below is the output for `nvim --version` after following nokodoko's solution
```
NVIM v0.7.0-dev+759-g7b8fbbdeb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by rushilmehra** [comment]
The problem is that you likely have an issue with your configuration file names conflicting with the plugin. For example, when configuring `nvim-cmp`, my config file was called `cmp.lua`. This however was conflicting with the plugin's files, and resulting in some weird behavior when I tried to load it up. Changing my config file to `_cmp.lua` worked (any different file name will work). 

Credit: https://github.com/nvim-telescope/telescope.nvim/issues/511

**Comment by Nokodoko** [comment]
I assumed that namespaces had already been taken into consideration. If
there is a naming collision, if would certainly impede the program from
loading properly.

Please let us know if that is the case.

Thanks!

**Comment by w-r-z-k** [comment]
Is LSP broken in 0.6.0?

**Comment by Nokodoko** [comment]
@w-r-z-k I can tell that the lsp handler that in the project doesn't like 0.6.0. I'm don't know if that means that it's broken, or if the handler that Chris is using doesn't work with 0.6.0. -- the current version is 0.7.0.

**Comment by Jacob3075** [comment]
I have placed the files in the namespace dir so the name conflicts shouldn't happen I guess.

**Comment by aleprovencio** [comment]
Not sure if this is the same issue as I don't get any errors, but the function `vim.diagnostic.config` is just not working for me with this config on both `neovim` `0.6` or `nightly`

**Comment by Nokodoko** [comment]
@aleprovencio  Hello! I do not think you are referencing the same issue.

That said I ran `:lua vim.diagnostic.config` command and did receive an error, but it's one that I believe has already been resolved. (`E5107: Error loading lua [string ":lua"]:1: '=' expected near '<eof>'`

From what I found, it appears that the healthcheck command for lua is skipped becasuse the `make_config` value is `nil`. (https://github.com/neovim/nvim-lspconfig/issues/248).
This isn't a stop the world event but might be a bug worth bringing back up to the neovim maintainers the 'healthcheck' command was suppose to be removed?

**Comment by aleprovencio** [comment]
You are right @Nokodoko, not only my problem has anything to do with this issue but I just found it was due to a bad snippet on my config I had not noticed, sorry about the noise.

**Comment by Nokodoko** [comment]
@aleprovencio hello! Interesting, I don't think this is a similar error. 

When I run `:lua vim.diagnostic.config` I receive an error: `E5107: Error loading lua [string ":lua"]:1: '=' expected near '<eof>'

    @aleprovencio  glad to hear you worked it out!

**Comment by Zeniku** [comment]
Make sure you have node installed and in
`:checkhealth` is happy

**Comment by Zeniku** [comment]
Because that's the thing that made it work for me
 In #35

**Comment by blfpd** [comment]
I got rid of the errors commenting the 3 places where `lsp/handlers.lua` is used. Might be coming from there.

**Comment by dotzenith** [comment]
Seems like this issue was related to node, atleast for me. Updating to the latest version of node/npm fixed it on my end

**Comment by Nokodoko** [comment]
The neovim git repo's HEAD doesn't always point to a stable release.
Sometimes you have to checkout earlier versions (if you are absolutely sure
that your word aren't due to out of date, or broken plugins).

The last nightly build shed to work just fine. But that's not always the
case, such is par for the course when using bleeding edge software.

**Comment by step0035** [comment]
@Nokodoko, I am also getting the same error `E5107: Error loading lua [string ":lua"]:1: '=' expected near '<eof>'`, in fact, I got this error running any `:lua` commands. Can you share how you resolve this issue? Thanks.

**Comment by A7Lavinraj** [comment]
> The problem is that you likely have an issue with your configuration file names conflicting with the plugin. For example, when configuring `nvim-cmp`, my config file was called `cmp.lua`. This however was conflicting with the plugin's files, and resulting in some weird behavior when I tried to load it up. Changing my config file to `_cmp.lua` worked (any different file name will work).
> 
> Credit: [nvim-telescope/telescope.nvim#511](https://github.com/nvim-telescope/telescope.nvim/issues/511)

that is right it fix my error thanks bro
