### ISSUE TITLE
Error after clonning repo

### ISSUE THREAD

**Issue by Pixfri** [ChristianChiarulli/Neovim-from-scratch#213]
When I open nvim after clonning the repo, I have this error
`E5113: Error while calling lua chunk: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:67: The coroutine failed with this message: Vim:E5248: Invalid character in a namespace
stack traceback:
        [C]: in function 'sign_define'
        .../packer/start/gitsigns.nvim/lua/gitsigns/signs/vimfn.lua:52: in function 'define_sign'
        .../packer/start/gitsigns.nvim/lua/gitsigns/signs/vimfn.lua:59: in function 'define_signs'
        .../packer/start/gitsigns.nvim/lua/gitsigns/signs/vimfn.lua:76: in function 'new'
        ...pack/packer/start/gitsigns.nvim/lua/gitsigns/manager.lua:443: in function 'setup'
        ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:412: in function <...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:390>
stack traceback:
        [C]: in function 'error'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:67: in function 'step'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:83: in function 'execute'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:114: in function 'setup'
        /home/jean/.config/nvim/lua/user/gitsigns.lua:6: in main chunk
        [C]: in function 'require'
        /home/jean/.config/nvim/init.lua:11: in main chunk
`

**Comment by msbrewer** [comment]
I get the same error, what I did was edit the init.lua and remove the require gitsigns line.  I tried a handful of fixes and couldn't get it to work.

**Comment by DarthWise** [comment]
if you on windows try to remove or rename "nvim-data" folder in %LocalAppData%

p.s.

no it didn't help.
First run without error. The error repeats on the second run.

**Comment by chas-kane** [comment]
I'm seeing the same thing; following the last line in the error message, commenting out line 11 in `init.lua` solves the issue.

**Comment by gnmearacaun** [comment]
Hi, this was fixed with #242
