### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by eric-delarosa** [ChristianChiarulli/Neovim-from-scratch#218]
Right after installing a fresh neovim and cloning the repo, I use `nvim` and I get this error:

`Error detected while processing /home/eric/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/eric/.config/nvim/lua/user/lsp/init.lua:8: attempt to index a boolean value
stack traceback:
        /home/eric/.config/nvim/lua/user/lsp/init.lua:8: in main chunk
        [C]: in function 'require'
        /home/eric/.config/nvim/init.lua:6: in main chunk
`

**Comment by Kodlak15** [comment]
Same issue for me. The error message went away when I commented out line 7 in $HOME/.config/nvim/lua/user/lsp/init.lua. 

That line is require("user.lsp.handlers").setup(), so something within the handlers.lua file seems to be going wrong.

**Comment by Kodlak15** [comment]
I just had the same issue. The problem went away after running the :PackerSync command. Give that a try and see if it solves your problem.

**Comment by LunZaiZai0223** [comment]
Hey, i was facing the same issue but after installed  cmp-nvim-lsp then everything good. Try to check whether you have installed cmp-nvim-lsp or not.

**Comment by snehalyelmati** [comment]
If PackerSync doesn't work in neovim, use this command directly in terminal.
`nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'`

**Comment by johnp41** [comment]
Had the same problem.. this [fix](https://github.com/LunarVim/Neovim-from-scratch/pull/49/files) helped me.

**Comment by gnmearacaun** [comment]
fixed by #49
