### ISSUE TITLE
Bufferline error Fedora 36

### ISSUE THREAD

**Issue by pedricm** [ChristianChiarulli/Neovim-from-scratch#219]
I had 2 errors in my bufferline.lua file.
1. I don't know why, but nvim was not able to recognize the guifg / guibg, I fixed it by repllacing guifg by fg and guibg by bg.
2. I have an error in the indicator icon: "'indicator_icon' will be deprecated: It should be changed to indicator and icon specified as indicator.icon, with indicator.style = 'icon' "

**Comment by brokenbeast** [comment]
how about you change "indicator_icon" to "indicator"? icon? i just ignore it

**Comment by geberl** [comment]
I use ...

```
bufferline.setup {
  options = {
    ...
    indicator = {
      icon = "▎",
      style = "icon"
    },
    ...
```
