### ISSUE TITLE
bad argument #1 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by shendypratamaa** [ChristianChiarulli/Neovim-from-scratch#24]
![Screenshot 2021-12-25 at 18 26 08](https://user-images.githubusercontent.com/76093597/147383944-f939fad9-e412-4035-b612-156f8a9345c9.png)

i dont have knowledge about lua actually for now, but with this im keep learn, i compare my code with this repo, i think its same, but i got error like this, what should i do bro ?, 

![Screenshot 2021-12-25 at 18 26 51](https://user-images.githubusercontent.com/76093597/147383965-a3ae531c-78b1-4baf-8111-928964cd5b1a.png)

**Comment by dushyantss** [comment]
I had the same error and the issue for me was that I didn't install `tamago324/nlsp-settings.nvim` by commenting it out in `lua/user/plugins.lua`.

`nlsp-settings` plugin is used to set the `default_schemas` variable in the `lua/user/lsp/settings/jsonls.lua`, which is not being loaded, thus staying nil.
```lua
local default_schemas = nil
local status_ok, jsonls_settings = pcall(require, "nlspsettings.jsonls")
if status_ok then
  default_schemas = jsonls_settings.get_default_schemas()
end
```

All I needed to do was uncomment this line
```lua
  use "tamago324/nlsp-settings.nvim" -- language server settings defined in json for
```
and run `:PackerSync`.(This should automatically run when saving `lua/user/plugins.lua`)

**Comment by shendypratamaa** [comment]
thanks for helping me @dushyantss 🙌

**Comment by Onkilchen** [comment]
Hey guys,

I have the exact same problem and no idea how to solve it. The error appeared after I updated the packer plugins. The line

`use "tamago324/nlsp-settings.nvim" -- language server settings defined in json for`

is uncommented, but I can't fix the problem. Help would be much appreciated!

Thanks

**Comment by dushyantss** [comment]
`nlsp-settings` changed how these schemas should be loaded. 

The way I solved it is by loading the json from their default schemas directly. I replaced the top of the file with the following:
```lua
local function read_json(file_path)
    local file = io.open(file_path, "r")
    local table = vim.fn.json_decode(file:read("a"))
    file.close()

    return table
end

local default_schemas = nil
local status_ok, nlspsettings = pcall(require, "nlspsettings")
if status_ok then
    local all_schemas = nlspsettings.get_default_schemas()
    for _, schema in ipairs(all_schemas) do
        if schema["fileMatch"][1] == "jsonls.json" then
            local file_path = schema["url"]
            default_schemas = read_json(file_path)
            break
        end
    end
end
```

All it does is that it finds the file in nlspsettings where the default schema is defined, parse that file into valid lua table and sets the default_schema to it.

There is most definitely a better way to solve this, but I severely lack in:
* knowledge of the libraries
* knowledge of lua
* time to gain the above knowledge

So, if this temporary solution helps, please use it. If someone has a better way, please update it here.

**Comment by igmt-official** [comment]
> `nlsp-settings` changed how these schemas should be loaded.
> 
> The way I solved it is by loading the json from their default schemas directly. I replaced the top of the file with the following:
> 
> ```lua
> local function read_json(file_path)
>     local file = io.open(file_path, "r")
>     local table = vim.fn.json_decode(file:read("a"))
>     file.close()
> 
>     return table
> end
> 
> local default_schemas = nil
> local status_ok, nlspsettings = pcall(require, "nlspsettings")
> if status_ok then
>     local all_schemas = nlspsettings.get_default_schemas()
>     for _, schema in ipairs(all_schemas) do
>         if schema["fileMatch"][1] == "jsonls.json" then
>             local file_path = schema["url"]
>             default_schemas = read_json(file_path)
>             break
>         end
>     end
> end
> ```
> 
> All it does is that it finds the file in nlspsettings where the default schema is defined, parse that file into valid lua table and sets the default_schema to it.
> 
> There is most definitely a better way to solve this, but I severely lack in:
> 
> * knowledge of the libraries
> * knowledge of lua
> * time to gain the above knowledge
> 
> So, if this temporary solution helps, please use it. If someone has a better way, please update it here.

Can you post your whole jsonls.lua? i have the same problem, but i really don't understand what part will i replace your code on jsonls.lua? cause im not familiar with lua.

**Comment by dushyantss** [comment]
Here you go, hope it helps.
```lua
local function read_json(file_path)
    local file = io.open(file_path, "r")
    local table = vim.fn.json_decode(file:read("a"))
    file.close()

    return table
end

local default_schemas = nil
local status_ok, nlspsettings = pcall(require, "nlspsettings")
if status_ok then
    local all_schemas = nlspsettings.get_default_schemas()
    for _, schema in ipairs(all_schemas) do
        if schema["fileMatch"][1] == "jsonls.json" then
            local file_path = schema["url"]
            default_schemas = read_json(file_path)
            break
        end
    end
end

local schemas = {
  {
    description = "TypeScript compiler configuration file",
    fileMatch = {
      "tsconfig.json",
      "tsconfig.*.json",
    },
    url = "https://json.schemastore.org/tsconfig.json",
  },
  {
    description = "Lerna config",
    fileMatch = { "lerna.json" },
    url = "https://json.schemastore.org/lerna.json",
  },
  {
    description = "Babel configuration",
    fileMatch = {
      ".babelrc.json",
      ".babelrc",
      "babel.config.json",
    },
    url = "https://json.schemastore.org/babelrc.json",
  },
  {
    description = "ESLint config",
    fileMatch = {
      ".eslintrc.json",
      ".eslintrc",
    },
    url = "https://json.schemastore.org/eslintrc.json",
  },
  {
    description = "Bucklescript config",
    fileMatch = { "bsconfig.json" },
    url = "https://raw.githubusercontent.com/rescript-lang/rescript-compiler/8.2.0/docs/docson/build-schema.json",
  },
  {
    description = "Prettier config",
    fileMatch = {
      ".prettierrc",
      ".prettierrc.json",
      "prettier.config.json",
    },
    url = "https://json.schemastore.org/prettierrc",
  },
  {
    description = "Vercel Now config",
    fileMatch = { "now.json" },
    url = "https://json.schemastore.org/now",
  },
  {
    description = "Stylelint config",
    fileMatch = {
      ".stylelintrc",
      ".stylelintrc.json",
      "stylelint.config.json",
    },
    url = "https://json.schemastore.org/stylelintrc",
  },
  {
    description = "A JSON schema for the ASP.NET LaunchSettings.json files",
    fileMatch = { "launchsettings.json" },
    url = "https://json.schemastore.org/launchsettings.json",
  },
  {
    description = "Schema for CMake Presets",
    fileMatch = {
      "CMakePresets.json",
      "CMakeUserPresets.json",
    },
    url = "https://raw.githubusercontent.com/Kitware/CMake/master/Help/manual/presets/schema.json",
  },
  {
    description = "Configuration file as an alternative for configuring your repository in the settings page.",
    fileMatch = {
      ".codeclimate.json",
    },
    url = "https://json.schemastore.org/codeclimate.json",
  },
  {
    description = "LLVM compilation database",
    fileMatch = {
      "compile_commands.json",
    },
    url = "https://json.schemastore.org/compile-commands.json",
  },
  {
    description = "Config file for Command Task Runner",
    fileMatch = {
      "commands.json",
    },
    url = "https://json.schemastore.org/commands.json",
  },
  {
    description = "AWS CloudFormation provides a common language for you to describe and provision all the infrastructure resources in your cloud environment.",
    fileMatch = {
      "*.cf.json",
      "cloudformation.json",
    },
    url = "https://raw.githubusercontent.com/awslabs/goformation/v5.2.9/schema/cloudformation.schema.json",
  },
  {
    description = "The AWS Serverless Application Model (AWS SAM, previously known as Project Flourish) extends AWS CloudFormation to provide a simplified way of defining the Amazon API Gateway APIs, AWS Lambda functions, and Amazon DynamoDB tables needed by your serverless application.",
    fileMatch = {
      "serverless.template",
      "*.sam.json",
      "sam.json",
    },
    url = "https://raw.githubusercontent.com/awslabs/goformation/v5.2.9/schema/sam.schema.json",
  },
  {
    description = "Json schema for properties json file for a GitHub Workflow template",
    fileMatch = {
      ".github/workflow-templates/**.properties.json",
    },
    url = "https://json.schemastore.org/github-workflow-template-properties.json",
  },
  {
    description = "golangci-lint configuration file",
    fileMatch = {
      ".golangci.toml",
      ".golangci.json",
    },
    url = "https://json.schemastore.org/golangci-lint.json",
  },
  {
    description = "JSON schema for the JSON Feed format",
    fileMatch = {
      "feed.json",
    },
    url = "https://json.schemastore.org/feed.json",
    versions = {
      ["1"] = "https://json.schemastore.org/feed-1.json",
      ["1.1"] = "https://json.schemastore.org/feed.json",
    },
  },
  {
    description = "Packer template JSON configuration",
    fileMatch = {
      "packer.json",
    },
    url = "https://json.schemastore.org/packer.json",
  },
  {
    description = "NPM configuration file",
    fileMatch = {
      "package.json",
    },
    url = "https://json.schemastore.org/package.json",
  },
  {
    description = "JSON schema for Visual Studio component configuration files",
    fileMatch = {
      "*.vsconfig",
    },
    url = "https://json.schemastore.org/vsconfig.json",
  },
  {
    description = "Resume json",
    fileMatch = { "resume.json" },
    url = "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/schema.json",
  },
}

local function extend(tab1, tab2)
    for _, value in ipairs(tab2) do
        table.insert(tab1, value)
    end
    return tab1
end

local extended_schemas = extend(schemas, default_schemas)

local opts = {
  settings = {
    json = {
      schemas = extended_schemas,
    },
  },
  setup = {
    commands = {
      Format = {
        function()
            vim.lsp.buf.range_formatting({}, { 0, 0 }, { vim.fn.line "$", 0 })
        end,
      },
    },
  },
}

return opts
```

**Comment by igmt-official** [comment]
> Here you go, hope it helps.
> 
> ```lua
> local function read_json(file_path)
>     local file = io.open(file_path, "r")
>     local table = vim.fn.json_decode(file:read("a"))
>     file.close()
> 
>     return table
> end
> 
> local default_schemas = nil
> local status_ok, nlspsettings = pcall(require, "nlspsettings")
> if status_ok then
>     local all_schemas = nlspsettings.get_default_schemas()
>     for _, schema in ipairs(all_schemas) do
>         if schema["fileMatch"][1] == "jsonls.json" then
>             local file_path = schema["url"]
>             default_schemas = read_json(file_path)
>             break
>         end
>     end
> end
> 
> local schemas = {
>   {
>     description = "TypeScript compiler configuration file",
>     fileMatch = {
>       "tsconfig.json",
>       "tsconfig.*.json",
>     },
>     url = "https://json.schemastore.org/tsconfig.json",
>   },
>   {
>     description = "Lerna config",
>     fileMatch = { "lerna.json" },
>     url = "https://json.schemastore.org/lerna.json",
>   },
>   {
>     description = "Babel configuration",
>     fileMatch = {
>       ".babelrc.json",
>       ".babelrc",
>       "babel.config.json",
>     },
>     url = "https://json.schemastore.org/babelrc.json",
>   },
>   {
>     description = "ESLint config",
>     fileMatch = {
>       ".eslintrc.json",
>       ".eslintrc",
>     },
>     url = "https://json.schemastore.org/eslintrc.json",
>   },
>   {
>     description = "Bucklescript config",
>     fileMatch = { "bsconfig.json" },
>     url = "https://raw.githubusercontent.com/rescript-lang/rescript-compiler/8.2.0/docs/docson/build-schema.json",
>   },
>   {
>     description = "Prettier config",
>     fileMatch = {
>       ".prettierrc",
>       ".prettierrc.json",
>       "prettier.config.json",
>     },
>     url = "https://json.schemastore.org/prettierrc",
>   },
>   {
>     description = "Vercel Now config",
>     fileMatch = { "now.json" },
>     url = "https://json.schemastore.org/now",
>   },
>   {
>     description = "Stylelint config",
>     fileMatch = {
>       ".stylelintrc",
>       ".stylelintrc.json",
>       "stylelint.config.json",
>     },
>     url = "https://json.schemastore.org/stylelintrc",
>   },
>   {
>     description = "A JSON schema for the ASP.NET LaunchSettings.json files",
>     fileMatch = { "launchsettings.json" },
>     url = "https://json.schemastore.org/launchsettings.json",
>   },
>   {
>     description = "Schema for CMake Presets",
>     fileMatch = {
>       "CMakePresets.json",
>       "CMakeUserPresets.json",
>     },
>     url = "https://raw.githubusercontent.com/Kitware/CMake/master/Help/manual/presets/schema.json",
>   },
>   {
>     description = "Configuration file as an alternative for configuring your repository in the settings page.",
>     fileMatch = {
>       ".codeclimate.json",
>     },
>     url = "https://json.schemastore.org/codeclimate.json",
>   },
>   {
>     description = "LLVM compilation database",
>     fileMatch = {
>       "compile_commands.json",
>     },
>     url = "https://json.schemastore.org/compile-commands.json",
>   },
>   {
>     description = "Config file for Command Task Runner",
>     fileMatch = {
>       "commands.json",
>     },
>     url = "https://json.schemastore.org/commands.json",
>   },
>   {
>     description = "AWS CloudFormation provides a common language for you to describe and provision all the infrastructure resources in your cloud environment.",
>     fileMatch = {
>       "*.cf.json",
>       "cloudformation.json",
>     },
>     url = "https://raw.githubusercontent.com/awslabs/goformation/v5.2.9/schema/cloudformation.schema.json",
>   },
>   {
>     description = "The AWS Serverless Application Model (AWS SAM, previously known as Project Flourish) extends AWS CloudFormation to provide a simplified way of defining the Amazon API Gateway APIs, AWS Lambda functions, and Amazon DynamoDB tables needed by your serverless application.",
>     fileMatch = {
>       "serverless.template",
>       "*.sam.json",
>       "sam.json",
>     },
>     url = "https://raw.githubusercontent.com/awslabs/goformation/v5.2.9/schema/sam.schema.json",
>   },
>   {
>     description = "Json schema for properties json file for a GitHub Workflow template",
>     fileMatch = {
>       ".github/workflow-templates/**.properties.json",
>     },
>     url = "https://json.schemastore.org/github-workflow-template-properties.json",
>   },
>   {
>     description = "golangci-lint configuration file",
>     fileMatch = {
>       ".golangci.toml",
>       ".golangci.json",
>     },
>     url = "https://json.schemastore.org/golangci-lint.json",
>   },
>   {
>     description = "JSON schema for the JSON Feed format",
>     fileMatch = {
>       "feed.json",
>     },
>     url = "https://json.schemastore.org/feed.json",
>     versions = {
>       ["1"] = "https://json.schemastore.org/feed-1.json",
>       ["1.1"] = "https://json.schemastore.org/feed.json",
>     },
>   },
>   {
>     description = "Packer template JSON configuration",
>     fileMatch = {
>       "packer.json",
>     },
>     url = "https://json.schemastore.org/packer.json",
>   },
>   {
>     description = "NPM configuration file",
>     fileMatch = {
>       "package.json",
>     },
>     url = "https://json.schemastore.org/package.json",
>   },
>   {
>     description = "JSON schema for Visual Studio component configuration files",
>     fileMatch = {
>       "*.vsconfig",
>     },
>     url = "https://json.schemastore.org/vsconfig.json",
>   },
>   {
>     description = "Resume json",
>     fileMatch = { "resume.json" },
>     url = "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/schema.json",
>   },
> }
> 
> local function extend(tab1, tab2)
>     for _, value in ipairs(tab2) do
>         table.insert(tab1, value)
>     end
>     return tab1
> end
> 
> local extended_schemas = extend(schemas, default_schemas)
> 
> local opts = {
>   settings = {
>     json = {
>       schemas = extended_schemas,
>     },
>   },
>   setup = {
>     commands = {
>       Format = {
>         function()
>             vim.lsp.buf.range_formatting({}, { 0, 0 }, { vim.fn.line "$", 0 })
>         end,
>       },
>     },
>   },
> }
> 
> return opts
> ```

thank you so much 🥰
