### ISSUE TITLE
Unable to insert in cloned files like ./config/neovim/init.lua

### ISSUE THREAD

**Issue by nairobi02** [ChristianChiarulli/Neovim-from-scratch#240]
![image](https://user-images.githubusercontent.com/109964994/195989829-c9582070-5785-4746-bb35-ac101c5c9232.png)

I can insert into other files, and it works well. 
But when I try to enter insert mode, I get this error. 
I can edit these files using other editors like nano, and those changes reflect when I open the file in nvim, but I cant enter insert mode in nvim for those files.

**Comment by gnmearacaun** [comment]
This was due to the switch to `mason` for installing lsp. Fixed on `master` and soon to be on the LSP branch.
