### ISSUE TITLE
crash on fresh install

### ISSUE THREAD

**Issue by Sparkenstein** [ChristianChiarulli/Neovim-from-scratch#254]
I just cloned the repo on a brand new windows 11 system, and when I start I get following error:

![image](https://user-images.githubusercontent.com/24642451/196890423-3dd64901-fba9-47dd-bb58-18183c565608.png)

The file `handler.lua` looks like this:

![image](https://user-images.githubusercontent.com/24642451/196890896-8f412e4f-0664-44c5-a7c0-e178cf97d58c.png)

I am on latest neovim
```
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

and `fb6e058104144d6d14ee96b2ae929ba2e5618a2d` commit (latest at the moment) of neovim-from-scratch

**Comment by gnmearacaun** [comment]
How is it now, any better?

**Comment by Sparkenstein** [comment]
I did another fresh install, was still getting same error, so I deleted `nvim-data` and now it looks fine. 
I am technically getting a mason error, `cc` , `gcc`... etc are not executables. but that's fine. setup is working. closing this now

**Comment by gnmearacaun** [comment]
Sweet. Yes sometimes it helps to blow away .cache/nvim. `:PackerResetCache`and `:PackerCompile` can also help. It sounds like you are missing some dependencies. Thanks for sharing.
