### ISSUE TITLE
No C compiler found

### ISSUE THREAD

**Issue by TJohn0312** [ChristianChiarulli/Neovim-from-scratch#274]
I've been stuck with this error for a bit and tried requireing "nvim-treesitter.install" in the .init.lua. 
Any tips on what else I should do?

[mason-lspconfig] automatically installing lua-language-server
Error detected while processing /home/tjohn0312/.config/nvim/init.lua:

No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.

my :checkhealth nvim-treesitter shows:

 ## Installation
- WARNING: `tree-sitter` executable not found (parser generator, only needed for :
TSInstallFromGrammar, not required for :TSInstall)
0K: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
0K: `git` executable found.
ERROR: `cc` executable not found.
- ADVICE:
     - Check that any of { vim. NIL, "cc", "gcc", "clang", "cl", "zig" } is in your $PATH or set 
        the environment variable CC or 'require"nvim-treesitter. install" . compilers explicitly!

0K: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be
compatible with runtime ABI.

**Comment by gnmearacaun** [comment]
It looks as though you are missing a c compiler. Is gcc installed on your system?  Treesitter is worried for that

**Comment by TJohn0312** [comment]
I installed minGW and then added minGW/bin to $PATH, and that seems to have gotten rid of that err. but I get a different compilation error:

on-nvim-open 
```
nvim-treesitter[json]: Error during compilation /usr/bin/ld: cannot find -lstdc++: No such file or directory collect2: error: ld returned 1 exit status
```
I get this err for all the languages, is there a way to route tree sitter to minGW?

**Comment by gnmearacaun** [comment]
install `ld` please

**Comment by wakywayne** [comment]
I am getting the same error how do I install gcc? Also I am unable to get the :TSUpdate comand to work

**Comment by Rishabh672003** [comment]
installl mingw-g++ that should fix you guys' issue

**Comment by snk-js** [comment]
your OS doesn't have c++ things:
`sudo apt-get install build-essential
`
be happy.

**Comment by jamaza7** [comment]
> Estuve atascado con este error por un tiempo e intenté requerir "nvim-treesitter.install" en .init.lua. ¿Algún consejo sobre qué más debo hacer?
> 
> [mason-lspconfig] instalando automáticamente lua-language-server Error detectado al procesar /home/tjohn0312/.config/nvim/init.lua:
> 
> ¡No se encontró ningún compilador de C! "cc", "gcc", "clang", "cl", "zig" no son ejecutables. ¡No se encontró ningún compilador de C! "cc", "gcc", "clang", "cl", "zig" no son ejecutables.
> 
> mi :checkhealth nvim-treesitter muestra:
> 
> ## Instalación
> * ADVERTENCIA: `tree-sitter`ejecutable no encontrado (generador analizador, solo necesario para: 
>   TSInstallFromGrammar, no requerido para: TSInstall) 
>   0K: `node`encontrado v18.12.1 (solo necesario para: TSInstallFromGrammar) 
>   0K: `git`ejecutable encontrado. 
>   ERROR: `cc`ejecutable no encontrado.
> * CONSEJO:
>   
>   * Compruebe que cualquiera de { vim. NIL, "cc", "gcc", "clang", "cl", "zig" } está en su $PATH o establezca 
>     la variable de entorno CC o 'require"nvim-treesitter. install". compiladores explícitamente!
> 
> 0K: Neovim se compiló con el tiempo de ejecución tree-sitter ABI versión 14 (requerido >=13). Los analizadores deben ser compatibles con el tiempo de ejecución ABI.



> 

Si estas en window solo necesitas instalar el paquete gcc: lo puedes hacer con scoop 
Res:= scoop install gcc
Con eso ya compila , y se soluciona tu error

**Comment by shanujha** [comment]
For anyone coming here for installation problem on Windows/ or CC, C++, GCC not available on Windows:

The easiest way is to use [skeeto's wdevkit](https://github.com/skeeto/w64devkit)
The install instructions are easy, like download, unzip and drop in.
You might have to put the `bin` folder on path depending on your application.

**Comment by Chrisbadill** [comment]
https://www.youtube.com/watch?v=dRxPUblx2SY

**Comment by Amzil-Mustapha** [comment]
> your OS doesn't have c++ things: `sudo apt-get install build-essential ` be happy.

Its Work !!

**Comment by 00EVA** [comment]
https://www.freecodecamp.org/news/how-to-install-c-and-cpp-compiler-on-windows/
for windows??

**Comment by rafay99-epic** [comment]
> It looks as though you are missing a c compiler. Is gcc installed on your system? Treesitter is worried for that

Brother, Then, how can I install a GCC or CC compiler on Windows 11? Any Idea?

**Comment by pranayaryal** [comment]
@rafay99-epic  check out https://www.freecodecamp.org/news/how-to-install-c-and-cpp-compiler-on-windows/ shared above. 

If you get "Local issuer certificate not found" errors, try this https://stackoverflow.com/questions/69348953/certificate-error-when-trying-to-install-msys2-packages-on-windows-server

उम्मीद है ये मदद करेगा

**Comment by rafay99-epic** [comment]
Okay,  Thanks brother.

**Comment by aborjav** [comment]
In case someone is straggling with this issue on Fedora (v38) just run:
`sudo dnf group install "C Development Tools and Libraries" "Development Tools"`
and check out: https://www.pragmaticlinux.com/2022/05/how-to-install-build-essential-on-fedora/

**Comment by rafay99-epic** [comment]
> @rafay99-epic check out https://www.freecodecamp.org/news/how-to-install-c-and-cpp-compiler-on-windows/ shared above.
> 
> If you get "Local issuer certificate not found" errors, try this https://stackoverflow.com/questions/69348953/certificate-error-when-trying-to-install-msys2-packages-on-windows-server
> 
> उम्मीद है ये मदद करेगा

Yeah Brother I have tried that on Windows, and the installing process keeps failing, so I am back to square one. But thanks for the help; I really appreciate it.

**Comment by rafay99-epic** [comment]
> In case someone is straggling with this issue on Fedora (v38) just run: `sudo dnf group install "C Development Tools and Libraries" "Development Tools"` and check out: https://www.pragmaticlinux.com/2022/05/how-to-install-build-essential-on-fedora/

I am using Fedora 38 right now and it's working so well. I had this problem but solved it a while ago, and there has been no issue since then.

**Comment by ceejay077** [comment]
try this:
```
1) sudo apt update
2) sudo apt-get install build-essential
```

**Comment by Rishabh672003** [comment]
how is this issue still not closed i think people have given enough solutions, so i will be closing it now
if someone is facing this issue open a new issue

**Comment by bAmrish** [comment]
> For anyone coming here for installation problem on Windows/ or CC, C++, GCC not available on Windows:
> 
> The easiest way is to use [skeeto's wdevkit](https://github.com/skeeto/w64devkit) The install instructions are easy, like download, unzip and drop in. You might have to put the `bin` folder on path depending on your application.

Thanks! This seems to be the easiest solutions for windows.

**Comment by m-deg** [comment]
I have gcc and cc on PATH for Windows. I am still getting the same error.. "No C compiler found!", any ideas?

**Comment by HabunoGD1809** [comment]
> https://www.freecodecamp.org/news/how-to-install-c-and-cpp-compiler-on-windows/ for windows??

Thank's you :D

**Comment by rustam-swe** [comment]
> your OS doesn't have c++ things: `sudo apt-get install build-essential ` be happy.

It worked for me, thank you! Debian 11

**Comment by leofab** [comment]
Solution that worked for me at windows 11
1. Install Chocolatey (if you haven't already):

Open PowerShell as Administrator, and run the following command:
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
2. Install GCC using Chocolatey:

```powershell
choco install mingw -y
```

**Comment by leesanghyun0414** [comment]
> Solution that worked for me at windows 11
> 
> 1. Install Chocolatey (if you haven't already):
> 
> Open PowerShell as Administrator, and run the following command:
> 
> ```powershell
> Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
> ```
> 
> 2. Install GCC using Chocolatey:
> 
> ```powershell
> choco install mingw -y
> ```

It's not worked for me with Windows11.
Still occured `No C compiler found!`

**Comment by blackmagezeraf** [comment]
> > It looks as though you are missing a c compiler. Is gcc installed on your system? Treesitter is worried for that
> 
> Brother, Then, how can I install a GCC or CC compiler on Windows 11? Any Idea?

Painless way to achieve this on Windows:
1. Install scoop. website-> https://scoop.sh/
2. Search gcc on their website for convenience here is the link to that as well: https://scoop.sh/#/apps?q=gcc&dm=false&s=0&d=1
3. Install the one you like from there. I would suggest to install the one from GNU as that is the one actively being maintained.

I used this exact method and it works like charm.

**Comment by RobiulMan** [comment]
> Solution that worked for me at windows 11
> 
> 1. Install Chocolatey (if you haven't already):
> 
> Open PowerShell as Administrator, and run the following command:
> 
> ```powershell
> Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
> ```
> 
> 2. Install GCC using Chocolatey:
> 
> ```powershell
> choco install mingw -y
> ```

### On Windows this works

**Comment by NestorSaad** [comment]
> your OS doesn't have c++ things: `sudo apt-get install build-essential ` be happy.

The final solution!!

**Comment by TroyMurphy** [comment]
I also ended up here from windows. Zig is significantly more lightweight and reliable for me.

`winget install zig.zig`

Restart terminal and open nvim, then nvim-treesitter started compiling
