### ISSUE TITLE
:qatar: nvim-treesitter[json]: Error during compilation

### ISSUE THREAD

**Issue by Galerien388** [ChristianChiarulli/Neovim-from-scratch#275]
I always get this error.
nvim-treesitter[json]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
Does anyone knows my problem?
Regards
Joel

**Comment by gnmearacaun** [comment]
Yes same error was reported a [couple of hours ago](https://github.com/LunarVim/Neovim-from-scratch/issues/274#issuecomment-1339836842). I have `ld` installed and I don't get that error. Is it installed?

**Comment by gnmearacaun** [comment]
when was the last time you ran :TSUpdate?

**Comment by Galerien388** [comment]
yes,  /usr/bin/ld is installed.
I think the problem started when I upgraded to Fedora 37.
I just went back to Fedora 36 and now everything is working fine. 
I'm going to keep using this version for a while.  (On my laptop also Fedora 37 I experience no problem)
So I'm not sure what causes the problem, but I happy it works again now. 
Thanks

**Comment by gnmearacaun** [comment]
Yes there was an issue on Fedora 37 I don't recall what it was. @LostNeophyte uses Fedora if you run into any other issues
