### ISSUE TITLE
how to get autocomplete for c/c++?

### ISSUE THREAD

**Issue by faizol** [ChristianChiarulli/Neovim-from-scratch#276]
Hi,

What plugin should I install to get an autocomplete for c/c++? 

Thank you.

**Comment by gnmearacaun** [comment]
I don't know much about it, but I can point you towards some resources of the Lunarvim organization. There's a Matrix/Discord room to get help with Neovim https://matrix.to/#/#neovim-atmachine:matrix.org 
There is a starter config for `c/c++` that may give you some ideas  https://github.com/LunarVim/starter.lvim/tree/c-ide 
The requirements are  `:MasonInstall clangd codelldb`
