### ISSUE TITLE
Markdown highlighting not working as expected

### ISSUE THREAD

**Issue by jordan-bravo** [ChristianChiarulli/Neovim-from-scratch#278]
I just installed Neovim From Scratch and haven't made any modifications yet.  Syntax highlighting seems to be working fine for all file types (Screenshot 1) *except* markdown files (Screenshot 2).

Is there any additional configuration I need to do?  I have done a search for this issue but found nothing.

Screenshot 1: File types other than markdown seem to have correct highlighting, e.g. lua:

![Screenshot 2022-12-14 at 09 22 53](https://user-images.githubusercontent.com/62706808/207628222-a9b9b232-f14b-408b-829f-ecbd65dd3cf3.png)

Screenshot 2: Markdown files seem to have random/broken highlighting:

![Screenshot 2022-12-14 at 09 23 27](https://user-images.githubusercontent.com/62706808/207628859-b7e449c2-5d60-4e1e-b0eb-61642b658c20.png)

**Comment by geberl** [comment]
The red words in your second screenshot are from Neovim's built in spellchecker. You can disable this in https://github.com/LunarVim/Neovim-from-scratch/blob/master/lua/user/autocommands.lua#L19

**Comment by jordan-bravo** [comment]
Thank you, that answers my question.

I will reference the Neovim `spell` options.

So does that mean markdown files don't get any syntax highlighting?

**Comment by Rishabh672003** [comment]
@jordan-bravo markdown files do get highlighting just do `:TSInstall markdown markdown_inline`

**Comment by jordan-bravo** [comment]
Thank you for your help.  

I am closing this issue since it is resolved.
