### ISSUE TITLE
The cmdheight is 2

### ISSUE THREAD

**Issue by huanhuanai** [ChristianChiarulli/Neovim-from-scratch#287]
How can i set cmdheight to 1. I tried adding “set cmdheight=1” to "init.vim", but it doesn't work. However the command ":set cmdheight=1" is valid.

**Comment by gnmearacaun** [comment]
You can set it in the options.lua file if you're using this config. Note that it is sourced in the init.lua file.

**Comment by gnmearacaun** [comment]
I agree `1` is better, however `2` gives more space to errors. For general neovim questions, please ask on [our Matrix chat](https://matrix.to/#/#neovim-atmachine:matrix.org)
