### ISSUE TITLE
Error while moving lines

### ISSUE THREAD

**Issue by lkabuci** [ChristianChiarulli/Neovim-from-scratch#292]
i get an error while moving a chunk of lines down
"E134: Cannot move a range of lines into itself"
https://github.com/LunarVim/Neovim-from-scratch/blob/2c7a64973602e8d9d18f6de75022014e96fa576a/lua/user/keymaps.lua#L54

**Comment by lkabuci** [comment]
I tried to use `keymap("v", "<A-k>", ":m .-2<CR>==gv", opts)`
but it didn't work

**Comment by Alexis12119** [comment]
Can you try this?
It's from my config and I think it works.
```
-- Move text up
vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv=gv")
-- Move text down
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv=gv")
```

**Comment by Alexis12119** [comment]
I would like to work on this issue. Can you assign it to me?
