### ISSUE TITLE
sumneko_lua is deprecated, use lua_ls instead. See :h deprecated

### ISSUE THREAD

**Issue by fromDisco** [ChristianChiarulli/Neovim-from-scratch#294]
Hello, i follow the fantastic NeoVim from Scratch Tutorial. I am a beginner in terms of NeoVim. 
From branch 06 there is the error message  "sumneko_lua is deprecated, use lua_ls instead."

I research a bit and found out, that this problem is due to renaming of the plugin. 
Will this be fixed in the repo, or will there be a guide, how to fix this? 

Thanks a lot
Michel

**Comment by Alexis12119** [comment]
You just need to rename `sumneko_lua` to `lua_ls` in your config and it'll work again perfectly.

**Comment by fromDisco** [comment]
Thanks a lot. Error warning is gone.

**Comment by trekie86** [comment]
You also need to rename lua/user/lsp/settings/sumneko_lua.lua to lua/user/lsp/settings/lua_ls.lua to gain the same configuration values back, such as the global vim ignore.

**Comment by trekie86** [comment]
I've raised a PR to address this deprecation warning on the 06-LSP branch. https://github.com/LunarVim/Neovim-from-scratch/pull/298

**Comment by Alexis12119** [comment]
Nice

**Comment by gnmearacaun** [comment]
Closed by #298
