### ISSUE TITLE
Error detected while processing function health#check

### ISSUE THREAD

**Issue by AxZxP** [ChristianChiarulli/Neovim-from-scratch#30]
I just copied the nvim folder in `~/.config` and check if all is good but `checkhealth` is raising an error :

```
Running healthchecks...
Error detected while processing function health#check:
line   37:
E684: list index out of range: 0
Press ENTER or type command to continue
```

## My setup
- MacOS Catalina
- I removed previous nvim folder in `~/.config`
- I removed previous nvim folder in ~/.local/share``
- I had a previous version of LunarVim that i removed prior to this setup.

Any idea on what can be wrong ?

**Comment by JohnVillalovos** [comment]
See here for fix: https://github.com/LunarVim/Neovim-from-scratch/issues/2#issuecomment-997300883
