### ISSUE TITLE
using fedora 38 and got lot of error

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [ChristianChiarulli/Neovim-from-scratch#303]
nvim-treesitter[json]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
nvim-treesitter[lua]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Creating temporary directory
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-css...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-yaml...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-python...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-bash...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-c...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-java...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-markdown...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-rust...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-typescript...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-javascript...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-markdown_inline...
[nvim-treesitter] [2/14, failed: 2] Extracting tree-sitter-tsx...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
[nvim-treesitter] [2/14, failed: 2] Compiling...
nvim-treesitter[css]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
nvim-treesitter[yaml]: Error during compilation
cc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.
nvim-treesitter[python]: Error during compilation
cc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.
nvim-treesitter[bash]: Error during compilation
cc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.
nvim-treesitter[c]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
nvim-treesitter[markdown]: Error during compilation
cc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.
nvim-treesitter[java]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
nvim-treesitter[javascript]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
nvim-treesitter[typescript]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
nvim-treesitter[markdown_inline]: Error during compilation
cc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.
nvim-treesitter[rust]: Error during compilation
nvim-treesitter[rust]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
[nvim-treesitter] [13/14, failed: 13] Compiling...
Press ENTER or type command to continue

nvim-treesitter[tsx]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
Press ENTER or type command to continue

**Comment by krafi-code** [comment]
To fix this issue i have to install 
`
sudo dnf install gcc gcc-c++ make
` 
please update the readme.md

but still i am seeing a issue 

**stack traceback:
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:200: in function 'get_query'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:91: in function 'get_query'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:169: in function 'prepare_query'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:288: in function 'iter_captures'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/indent.lua:50: in function 'fn'
        ...r/start/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:356: in function 'get_indents'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/indent.lua:98: in function 'get_indent'
        ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:466: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
**

**Comment by krafi-code** [comment]
https://github.com/RRethy/vim-illuminate/issues/166
https://github.com/nvim-treesitter/nvim-treesitter/issues/4813

**Comment by vulekhanh** [comment]
Hi, are you still encountering error?

**Comment by ghost** [comment]
hey not sure if this is the exact same issue but im on fedora and getting this on launch with nothing changed:

`[lspconfig] Cannot access configuration for lua_ls. Ensure this server is listed in `server_configurations.md` or added as a custom
server.
[mason-lspconfig] automatically installing pyright
[mason-lspconfig] automatically installing json-lsp
Error detected while processing /home/ostap-timur-tymchenko/.local/share/nvim/site/pack/packer/start/nvim-treesitter/plugin/nvim-tre
esitter.lua:
E5113: Error while calling lua chunk: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:586: Overriding has-ancestor?
stack traceback:
        [C]: in function 'error'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:586: in function 'add_predicate'
        ...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:74: in main chunk
        [C]: in function 'require'
        ...ack/packer/start/nvim-treesitter/lua/nvim-treesitter.lua:8: in main chunk
        [C]: in function 'require'
        .../packer/start/nvim-treesitter/plugin/nvim-treesitter.lua:9: in main chunk
Error detected while processing /home/ostap-timur-tymchenko/.local/share/nvim/site/pack/packer/start/nvim-ts-context-commentstring/p
lugin/ts_context_commentstring.vim:
line    1:
E5108: Error executing lua ...s-context-commentstring/lua/ts_context_commentstring.lua:4: loop or previous error loading module 'nvi
m-treesitter'
stack traceback:
        [C]: in function 'require'
        ...s-context-commentstring/lua/ts_context_commentstring.lua:4: in function 'init'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue`

**Comment by gnmearacaun** [comment]
It has to do with an update to treesitter and that your parsers [may be incompatable](https://github.com/nvim-treesitter/nvim-treesitter/issues/3092#issue-1288690088)
What happens if you `git pull` (or `git fetch upstream` && `git merge upstream/master`) and `:TSUpdate`

**Comment by d3vv3** [comment]
For me it was the `sudo dnf install g++`

**Comment by arantebw** [comment]
> For me it was the `sudo dnf install g++`

I have a new machine, so `g++` and its dependencies were missing, this works for me.

**Comment by Brikkel** [comment]
> To fix this issue i have to install `sudo dnf install gcc gcc-c++ make` please update the readme.md
> 
> but still i am seeing a issue
> 
> **stack traceback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:200: in function 'get_query' ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:91: in function 'get_query' ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:169: in function 'prepare_query' ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:288: in function 'iter_captures' ...ker/start/nvim-treesitter/lua/nvim-treesitter/indent.lua:50: in function 'fn' ...r/start/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:356: in function 'get_indents' ...ker/start/nvim-treesitter/lua/nvim-treesitter/indent.lua:98: in function 'get_indent' ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:466: in function '' vim/_editor.lua: in function <vim/_editor.lua:0> *

Finally, installing gcc-c++ fixed all my tresitter issues

**Comment by View-my-Git-Lab-krafi** [comment]
thanks to everyone , i dont know this issue is reinvent with present fedora version and neonim ,  thanks for your time, bye
