### ISSUE TITLE
E5248 because of typo in bufferline.lua

### ISSUE THREAD

**Issue by darcyparker** [ChristianChiarulli/Neovim-from-scratch#312]
https://github.com/LunarVim/Neovim-from-scratch/blob/master/lua/user/bufferline.lua#L75

For nvim 0.9, this line should be:
`fg = { attribute = "fg", highlight = "Visual" }`

Otherwise there is an E5248  error when starting nvim. See discussion here:
https://github.com/akinsho/bufferline.nvim/issues/724#issuecomment-1501185320

**Comment by gnmearacaun** [comment]
thank-you very much.

We're v9.0 ready!
