### ISSUE TITLE
Failed to install nvim-telescope/telescope.nvim

### ISSUE THREAD

**Issue by bmrussell** [ChristianChiarulli/Neovim-from-scratch#4]
As per title, on intial clone. Missing an external dependency?

- Fedora 34 (nvim 0.5.1)
- Ubuntu Ubuntu 20.04.3 WSL (nvim 0.5.1)
- Windows (nvim 0.6.0)

**Comment by ChristianChiarulli** [comment]
This sometimes just happens if the connection times out, just do another `:PackerUpdate` or `PackerSync`
