### ISSUE TITLE
[Wanted Help] Showing multiple language servers choice 

### ISSUE THREAD

**Issue by touhidulshawan** [ChristianChiarulli/Neovim-from-scratch#42]
![2022-01-05_15-00](https://user-images.githubusercontent.com/37136490/148190101-a579b980-9c13-4b46-806b-ddd49b191ce1.png)
I am encountering this problem after using the null-ls-nvim. Every time I have to choose one of theme? I can not figure out the problem. what should I do?

**Comment by rolfb** [comment]
It may depend on the file type, but if you go to your local version of https://github.com/LunarVim/Neovim-from-scratch/blob/master/lua/user/lsp/settings/jsonls.lua#L180, probably `~/.config/nvim/lua/user/lsp/settings/jsonls.lua`
and add the following above the line which says `settings = {`
```lua
init_options = {
  provideFormatter = false,
},
```
Close and re-open neovim and then it should stop trying to provide a formatter from jsonls which may be the cause of this.

**Comment by rolfb** [comment]
Tiny caveat, I don't actually know if json-ls provides formatters so setting it to false may be too heavy-handed.
Perhaps someone else can clarify if setting it to false can become problematic later.
