### ISSUE TITLE
Wiring up emmet-ls so that completions work?

### ISSUE THREAD

**Issue by jmdfm** [ChristianChiarulli/Neovim-from-scratch#46]
I've tried using `emmet-ls` and the various forks - and the config suggested in a comment on the LunarVim repo, but none of them seem to trigger a completion in this setup. I can do `:LspInfo` and see that the language server has attached to the buffer, but typing something like `div.border` doesn't translate into the html that it should. 

Any suggestions?

**Comment by jmdfm** [comment]
Figured it out, `emmet-ls` does not support `erb` out of the box. Had to fork it and add the languageId.

**Comment by kathirr007** [comment]
@johnmcdowall any help on how to resolve would be helpful
