### ISSUE TITLE
config not working when using sudo

### ISSUE THREAD

**Issue by ghost** [ChristianChiarulli/Neovim-from-scratch#53]
when i use neovim to edit any file that i can edit (config files) the config works, but when i use sudo nvim to edit a file that i can't edit (.desktop) neovim uses the defult config

**Comment by nishu-murmu** [comment]
It has nothing to do with Neovim or it's config. Check out this [reddit](https://www.reddit.com/r/neovim/comments/hw1zc9/sudo_nvim_not_a_thing/)

**Comment by ghost** [comment]
how can i use neovim as the defult sudoedit editor

**Comment by abuturabofficial** [comment]
`/root/` user checks for neovim config in `/root/.config/nvim/`, when not found, it'll use nvim default config.It's not an issue if you edit system files not very often, if the case is otherwise you can copy `~/.config/nvim` to `/root/.config/nvim`

**Comment by ghost** [comment]
but then when i make a change in my neovim config i have to copy it and i want a better solution

**Comment by abuturabofficial** [comment]
> but then when i make a change in my neovim config i have to copy it and i want a better solution

You can symlink, your home config to `/root/`, but do it at your own risk, as there are some security concerns relating it especially in multi user systems, do your research before using this method.

**Comment by ghost** [comment]
Thank you so much
