### ISSUE TITLE
Pyright not showing diagnostics

### ISSUE THREAD

**Issue by ghost** [ChristianChiarulli/Neovim-from-scratch#6]
I installed the pyright language server. When writing a python file, it's showing me where errors are, but I'm not getting any on screen message and I'm unsure how to view what the error is?

I'm not sure if this is a me issue or what?

![image](https://user-images.githubusercontent.com/19592432/146618143-19fd4358-cb4b-4445-910c-ad45b6e2eb8c.png)

**Comment by ChristianChiarulli** [comment]
press `gl` or turn on virtualtext in the `handler.lua` file
