### ISSUE TITLE
"jk" for Esc keymap doesn't work on macOS

### ISSUE THREAD

**Issue by znb** [ChristianChiarulli/Neovim-from-scratch#76]
I'm not sure if I'm the only person with this issue, but for some reason the "jk" keymap for Esc doesn't appear to work on macOS 12.2.

I'm using Neovim v0.6.1 installed via Homebrew.

The keymap works fine if I remap to anything else. It appears to work if you hit the combo extremely quickly but I suspect there may be something else causing the issue. 

`keymap("i", "jk", "<Esc>", opts)`

I don't have any major changes to the NFS configuration.

**Comment by ChristianChiarulli** [comment]
change timeoutlen to 1000 in options.lus, but then you'll notice whichkey opens slowly, my ideal scenario would be to have them work on different timers but I don't think it's possible

**Comment by znb** [comment]
Ah, that makes sense. 

I've set timeoutlen to 220 and it's a happy middle ground for me.

Thanks for the help. 
And thank you for Neovim-from-Scratch...I'm really enjoying it.
