### ISSUE TITLE
When I run nvim, It didn't start install plugins 

### ISSUE THREAD

**Issue by U-DI-Page** [ChristianChiarulli/Neovim-from-scratch#89]
I have cloned the respositry locally, but it seems didn't work to me.
I have try to reInstall the neovim, and my neovim's version is 0.6.1,I use brew to install it.

**Comment by nishu-murmu** [comment]
Did you run `:PackerInstall`?
Are your files inside `.config/nvim` directory?

**Comment by U-DI-Page** [comment]
> Did you run `:PackerInstall`? Are your files inside `.config/nvim` directory?

Thanks for the answer, I thought it could install automatically, i didn't know there is a command to install it.

And I have another question, Now I try to install the plugins, but all failed,'kill git due to timeout'. 

Is there has  another way to install the plugins?

**Comment by U-DI-Page** [comment]
> > Did you run `:PackerInstall`? Are your files inside `.config/nvim` directory?
> 
> Thanks for the answer, I thought it could install automatically, i didn't know there is a command to install it.
> 
> And I have another question, Now I try to install the plugins, but all failed,'kill git due to timeout'.
> 
> Is there has another way to install the plugins?

retry one hundred times, finally success
