### ISSUE TITLE
Tsserver not attaching to buffer

### ISSUE THREAD

**Issue by zakissimo** [ChristianChiarulli/Neovim-from-scratch#94]
Despite me having installed tsserver with LspInstallInfo and ran 
```
npm -g install typescript typescript-language-server
```

I can't get tsserver to attach when I open a .js or .jsx file.

![image](https://user-images.githubusercontent.com/64891486/155886038-a33031da-8bfb-41ec-bbba-77fb79b31058.png)

I do have handlers.lua and lsp-installer.lua but still ... I don't know what I'm missing.

**Comment by arsize** [comment]
metoo...

**Comment by zakissimo** [comment]
> metoo...

I use quick_lint_js for now ...

**Comment by zakissimo** [comment]
Turns out it's by design you need a .git or a config file for the tsserver to find the root directory and start properly.
See here : https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver
On the "root_dir" part. This is what type of file says to tsserver that it is in a root directory.

**Comment by mpcabete** [comment]
OMG @zakissimo, I have spent a few hours trying to find out why tsserver was not working with my .js file. After I ran a `git init` it worked! There should definitely be a more explicit error message...
