### ISSUE TITLE
Using cmp with copilot

### ISSUE THREAD

**Issue by ogirginc** [ChristianChiarulli/Neovim-from-scratch#95]
Has anyone find a way to use tab with both cmp and copilot?

I went over the issue list on [cmp](https://github.com/hrsh7th/nvim-cmp/issues?q=is%3Aissue+sort%3Aupdated-desc+copilot+is%3Aclosed). My current way is https://github.com/jose-elias-alvarez/dotfiles/commit/7ab0a3d66915b5d97f01b8bc0815ac50af9a7ed1, but even though Copilot's suggestion is overlaid, it cannot be selected with tab.

**Comment by suciptoid** [comment]
I've same [configuration](https://github.com/suciptoid/nvim/blob/master/lua/user/cmp.lua#L68-L83) on tab keymap, and you should dismiss cmp completion first and press tab to use copilot completion (same behaviour on VSCode, if copilot suggestion shown, completion is hidden).

Or you can prioritize copilot first by moving `copilot_keys ~= ""` on before `cmp.visible()`.

**Comment by ogirginc** [comment]
@suciptoid thank you very much! Your config works great! 👏

**Comment by felangga** [comment]
> configuration

sadly your file is not found 😢

**Comment by suciptoid** [comment]
@felangga you can refer this commit: https://github.com/ogirginc/dotfiles/commit/82d9a01c985ff095aba4c1669cfdf2dffcd4a8de by @ogirginc 

Now i'm using https://github.com/LazyVim/LazyVim so my config for neovim from scratch is overwritten, sorry 😄

**Comment by ogirginc** [comment]
I have also switched to the LazyVim and would highly recommend it 😅
