### ISSUE TITLE
i'm f*** done with removing nvim directory

### ISSUE THREAD

**Issue by sefatanam** [ChristianChiarulli/Neovim-from-scratch#97]

**Comment by frhgm** [comment]
I also got frustrated last night doing the same, trying the config to work for me, unsuccesfully. Is that why you were removing nvim folders?

**Comment by sefatanam** [comment]
@rafamadriz  yes, https://youtu.be/ZvhzrltuA9U watch this video. I got this video helpful i tried with Ubuntu 20.04 & got success in first attempt.

**Comment by frhgm** [comment]
Great, I'll take a look at it. Thanks!
As a side note, I think I will go through C@M entire tutorial on this repo, maybe I can diagnose better what my problem is by going through it step by step. Although both configs look good

**Comment by frhgm** [comment]
I'm sorry for flooding this "issue" with comments, but just wanted to say that my problem was that I wasn't on neovim's lastest version, 0.7 (I noticed that the README.md had an commit that mentioned 0.7). All is working correctly for me now.

**Comment by sefatanam** [comment]
okay, I didn't find out what's going wrong with my config. Maybe this version miss-matched.

**Comment by frhgm** [comment]
In the end, my OS probably isn't very clean after everything I installed hoping it worked, but before I ran the config last time, I tried to get as many green checks on :checkhealth, and then it worked for me. Maybe it was a version miss match, or something else. Let me know if I can help you
